### ISSUE TITLE
composer serve command not found exception

### ISSUE THREAD

**Issue by Nohossat** [wearenolte/lean-theme#116]
Hi there, 

I managed to install the theme but when I want to use the Development mode (composer serve), I have a CommandNotFoundException message. Is there a workaround to enable it ?

Composer version : 1.8.3 (2019-01-30)
mac OS: Mojave

**Comment by Nohossat** [comment]
Update: for now i'm using `cd frontend && npm run serve` to enable the dev mode

**Comment by jeffreynolte** [comment]
Thank you @Nohossat. Would you mind creating a PR with an update for those who come later with the same issue?

**Comment by Nohossat** [comment]
Sure !

**Comment by arzola** [comment]
@Nohossat thank you for your contribution fixed with your PR #117
