### ISSUE TITLE
Provide access to install plugins via WordPress Admin

### ISSUE THREAD

**Issue by jeffreynolte** [wearenolte/lean-theme#185]
**Current**
When logged into WordPress as an admin there is no ability to add plugins to the site via the admin.

**Expected**
When logged into WordPress admin I can install plugins as a normal admin user.

**Steps to reproduce**
1. Login to WordPress as admin
2. Go to plugins
3. Observe no "Add New" plugin option

**Comment by NolteDeveloper** [comment]
This isn't a Lean issue, it's a wp-config setting, nothing to do with the theme.

**Comment by jeffreynolte** [comment]
N/a
