### ISSUE TITLE
Add hooks on theme activation

### ISSUE THREAD

**Issue by mitogh** [wearenolte/lean-theme#31]
To test: 

- PHP Version
- WP Version

Since some features of the theme does not work on all PHP version.

Also it might be useful to setup the requirements on the wiki of the project.

**Comment by adamf321** [comment]
I would say this is lower priority, as we control these things. But agree it is a nice to have.

**Comment by mitogh** [comment]
Sounds good move to `Nice to have` but yes I think is easier to deactivate the theme and send a notification with the reason in case the requirements are not present we can add test for plugins as well so we avoid having warning or white pages before any plugin is active.
