### ISSUE TITLE
Add filters and hooks on any custom option

### ISSUE THREAD

**Issue by mitogh** [wearenolte/lean-theme#33]
For make it easier to extend or update certain areas we need  to add filters and hooks on as much as possible. 

So we avoid having to touch the base or boilerplate code every time.

**Comment by adamf321** [comment]
We should have a naming convention for the hooks. I like the way ACF does it using `/`s. E.g. `lean/something_filter`.

**Comment by mitogh** [comment]
Yes I think we can use the convention all around with the prefix `lean/` even for the actions I think.
