### ISSUE TITLE
See if posible to create a parent theme 

### ISSUE THREAD

**Issue by mitogh** [wearenolte/lean-theme#35]
IF we find a lot of boilerplate code that is not part of a project it would makes more sense to have this theme as a parent theme instead so we have only code of a project in the theme as child.

At the moment this can be put in hold as we don't have a final version of the files, assets, etc.

**Comment by Rulox** [comment]
Do you think the parent theme is still a good idea for this? Or are we kind of using it as a boilerplate to create our own projects @mitogh  ?

**Comment by mitogh** [comment]
The original idea was to have the parent theme with all the default configurations that never change such as define things like: 

- ACF Structure
- Fields
- Autoloading and so on

So we have only the patterns and meaningful templates for the child theme in that way the parent theme can be installed via composer as a dependency of the site also the project theme is going to have only things that are related with the project. 

Let me know what do you think @Rulox

**Comment by Rulox** [comment]
I think is fine I'm just wondering what's the gain on this. The only pro that I can think of is that is easier to update because we can just update the main theme when we want to make some changes.
