### ISSUE TITLE
Change footer and header code for hooks

### ISSUE THREAD

**Issue by mitogh** [wearenolte/lean-theme#43]
I think things like: 

- https://github.com/moxie-lean/lean-theme/blob/master/header.php#L24-L28
- https://github.com/moxie-lean/lean-theme/blob/master/footer.php#L11

Can be used as place to put some hooks like https://github.com/zamoose/themehookalliance does. So we can inject code on those areas from any plugin, or child theme if we want to move forward with: https://github.com/moxie-lean/lean-theme/issues/35. I think this kind of related with https://github.com/moxie-lean/lean-theme/issues/33

**Comment by adamf321** [comment]
Where would we put the code to inject the JS in this example?

**Comment by mitogh** [comment]
This is more like in terms of extensibility since if we have a base theme where the `header.php` and `footer.php` is defined on the parent theme any child or plugin theme can override easily what's defined on the initial file. JS can be injected inside of a div created by the hook like: 

```php
<?php
add_action( 'lean/before_body', function() {
?>
   <div id="my-custom-section"></div>
<?php
});
```

```js
const section = document.querySelector( '#my-custom-section' );
// Do something with section.
```
