### ISSUE TITLE
Create generator of patterns

### ISSUE THREAD

**Issue by Fcog** [wearenolte/lean-theme#84]
example: 
command: yo organism slideshow
will create in organisms folder
slideshow/slideshow.php (with initial template)
slideshow/_slideshow.scss

and adds _slideshow.scss to organisms/style.scss

**Comment by mitogh** [comment]
Sounds like a good CLI tool for the weekend @Fcog good idea BTW

**Comment by Rulox** [comment]
It can be a npm module so we can run it with composer/npm and we don't add another dependency, what do you think? @Fcog

**Comment by mitogh** [comment]
NPM should be better as you can install a CLI pretty easy in that way, and doesn't have to be a dependency of the project as is not required as well.

**Comment by Rulox** [comment]
Yeah I was thinking of a npm script, and maybe a composer "fake" script that calls the npm, just to keep everything under composer for consistency
