### ISSUE TITLE
Import sass automatically

### ISSUE THREAD

**Issue by Rulox** [wearenolte/lean-theme#85]
At the moment we have to add the route of the _sass file manually when we create a new component. Do this automatically.

**Comment by mitogh** [comment]
I think this has to be PHP or JS script generating those files as SASS does not have this feature yet

**Comment by mitogh** [comment]
See https://github.com/moxie-lean/lean-theme/issues/26

**Comment by Rulox** [comment]
Yes it has to be a script that checks in all the folders and create a main sass file with all the imports in the order we want, and then we compile that one.
