### ISSUE TITLE
Improve init of the theme.

### ISSUE THREAD

**Issue by Rulox** [wearenolte/lean-theme#86]
After having a look at Barrel's theme, I really like the way they have a standard on how to init the theme (where to add the cpts, taxonomies etc).

We have pretty much everything else in common (we have it in composer modules),  but maybe we can create a couple of empty functions like "add_cpts"... so it would help to keep everything standarized?

Ref.
https://gitlab.com/barrel/barrel-base-theme/blob/master/wp-content/themes/barrel-base/lib/class-base-theme.php

What do you think about this?

**Comment by mitogh** [comment]
I'm not really sure as if you have 3 CPTs and each 3 taxonomies it can become quite messy we should define something similar using Autoload I guess it would be more cleaner.
